// app/layout.tsx
import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// Pretendard 폰트 설정
const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2", //  public/fonts에 폰트 파일
  display: "swap",
  variable: "--font-pretendard",
});

// Geist Mono (기존 코드 유지)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body className={`${pretendard.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}